### PR TITLE
fix(prettier-plugin-sentences-per-line): keep indentation while dealing with list

### LINKED ISSUE #869: 🐛 Bug: prettier-plugin-sentences-per-line - Indentation is not preserved for list items that span multiple lines
### Bug Report Checklist

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have pulled the latest `main` branch of the repository.
- [x] I have [searched for related issues](https://github.com/JoshuaKGoldberg/sentences-per-line/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

Consider the following `md` snippet with a list item.

```text
- `Array<string>` - to specify an array of top-level package properties to lint sorting on only those properties.
   All properties not in this collection will be sorted by "sort-package-json" specifications.
```

List items containing multiple phrases across multiple lines should maintain consistent indentation.

### Actual

At the moment the second line indentation is stripped producing the following output:

```text
- `Array<string>` - to specify an array of top-level package properties to lint sorting on only those properties.
All properties not in this collection will be sorted by "sort-package-json" specifications.
```

Removing  `prettier-plugin-sentences-per-line` proceeds the expected behaviour.

### Additional Info

- Coming from https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/pull/1500#issuecomment-3708203854

`md` complete snippet can be found here: https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/blob/eeff2b8af576e503a155b72313ac9e69807c48c2/docs/rules/order-properties.md?plain=1#L56-L57

### PR DESCRIPTION
**Pull request by marcalexiei**
## PR Checklist

- [x] Addresses an existing open issue: fixes #869
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/sentences-per-line/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/sentences-per-line/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

This PR prevents indentation loss when splitting list items that contain multiple sentences across multiple lines.

### Implementation details

- Group `sentence` nodes to ensure correct interaction with parent line breaks.
- Insert explicit `sentenceBreak` nodes after sentence-ending words during a single, root-level AST pass.
- Render `sentenceBreak` nodes using a forced parent break followed by a line break, ensuring one sentence per line while preserving list indentation.

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
Whoo, awesome! This is some intricate stuff in areas I'm not super familiar with (and have been helped by @fisker in the past). This looks great to me - if you have time to review this week @fisker I'd appreciate it. But if not I'll merge next week or so. Thanks! 🔥

File: packages/prettier-plugin-sentences-per-line/src/index.ts [hunk 1]
```diff
@@ -24,15 +25,37 @@ export const parsers = {
...
+			customAbbreviations,
+		});
+	}
+
+	/** print sentence (MUST be grouped to be used in conjunction with {@link breakParent}) */
+	if (node.type === "sentence") {
+		return group(
+			// @ts-expect-error -- Prettier's AstPath.call typings cannot express that
+			// `children` here is `Nodes[]`; TypeScript infers `string`
+			node.children.map((_, i: number) => path.call(print, "children", i)),
```
Comment (fisker) [inline packages/prettier-plugin-sentences-per-line/src/index.ts]:
```suggestion
			path.map(print, "children"),
```

**Comment by fisker** [comment]
I didn't look deep, but looks good to me.

Ideally intercept the `sentence` print logic should enough without AST mutation, but I can be wrong. (Mentioned before when talking to @JoshuaKGoldberg)

**Comment by fisker** [comment]
There'is also a `getVisitorKeys` function in printer, maybe need add `sentenceBreak` to it (can cause error in theory), but I guess it can't be inside other Node? If so, should be safe to ignore.

File: packages/prettier-plugin-sentences-per-line/src/index.ts (hunk 1 above)
Comment (marcalexiei) [reply packages/prettier-plugin-sentences-per-line/src/index.ts]: Much better! Thanks 🙇

File: packages/prettier-plugin-sentences-per-line/src/index.ts [hunk 2]
```diff
@@ -21,18 +22,68 @@ export const parsers = {
...
+		case "sentence":
+			return ["children"];
+
+		case "sentenceBreak":
+			return [];
+
+		default:
+			return mdastPrinter.getVisitorKeys?.(node, nonTraversableKeys) ?? [];
+	}
+};
```
Comment (marcalexiei) [inline packages/prettier-plugin-sentences-per-line/src/index.ts:111]: > There'is also a getVisitorKeys function in printer, maybe need add sentenceBreak to it (can cause error in theory), but I guess it can't be inside other Node? If so, should be safe to ignore.

Make sense to have it. Just to be sure 😅.

File: packages/prettier-plugin-sentences-per-line/src/modifications/modifyNodeIfMultipleSentencesInLine.ts
Comment (marcalexiei) [inline packages/prettier-plugin-sentences-per-line/src/modifications/modifyNodeIfMultipleSentencesInLine.ts:1]: > Ideally intercept the sentence print logic should enough without AST mutation, but I can be wrong.

I have not tried that approach. I chose to work at the AST level because it offers fine-grained control, and I assumed that introducing a custom node and letting Prettier handle the printing logic would be the most reliable way to ensure correct indentation.

This is my first time working on a Prettier plugin, so I may be making incorrect assumptions.

**Review by marcalexiei — COMMENTED** [review]
Thanks for the quick review!
I think I’ve addressed the feedback, let me know if there’s anything else I can improve.

File: packages/prettier-plugin-sentences-per-line/src/modifications/modifyNodeIfMultipleSentencesInLine.ts [hunk 3]
```diff
@@ -1,61 +1,69 @@
...
 export interface ModifyNodeOptions {
 	customAbbreviations?: string[];
 }
 
+/**
+ * This function mutates the AST structure (inserts SentenceBreak nodes),
+ * but only once per printed document.
+ * It receives an AstPath for the root.
+ * Caller should ensure it's only invoked for the root node).
+ */
```
Comment (fisker) [inline packages/prettier-plugin-sentences-per-line/src/modifications/modifyNodeIfMultipleSentencesInLine.ts:16]: you can do it in printer.preprocess, after the original processed. 😄

Comment (marcalexiei) [reply packages/prettier-plugin-sentences-per-line/src/modifications/modifyNodeIfMultipleSentencesInLine.ts:16]: addressed by https://github.com/JoshuaKGoldberg/sentences-per-line/pull/871/changes/269a50382dd55775d4e0dbc7c28132a1e0401d2c

**Review by fisker — APPROVED** [review]

File: packages/prettier-plugin-sentences-per-line/src/modifications/modifyNodeIfMultipleSentencesInLine.ts [hunk 4]
```diff
@@ -1,61 +1,70 @@
...
+			}
+
+			// Insert structural break
+			children.splice(i + 1, 0, { type: "sentenceBreak" });
+		}
+	}
+}
+
+function walk(
+	node: Root | RootContent,
```
Comment (JoshuaKGoldberg) [inline packages/prettier-plugin-sentences-per-line/src/modifications/modifyNodeIfMultipleSentencesInLine.ts]: [Types] The `child` below isn't `RootContent`, it's a `SentenceNodeChild`. Which this function does support. Therefore:

```suggestion
	node: Root | RootContent | SentenceNodeChild,
```

File: packages/prettier-plugin-sentences-per-line/src/index.ts [hunk 5]
```diff
@@ -20,19 +21,101 @@ export const parsers = {
...
+
+	/**
+	 * `sentenceBreak` nodes force a hard line break at the parent level by
+	 *  emitting a {@link breakParent} followed by a {@link line}.
+	 */
+	if (node.type === "sentenceBreak") {
+		return [breakParent, line];
+	}
+
+	// Fallback to Prettier's original mdast printer
```
Comment (JoshuaKGoldberg) [inline packages/prettier-plugin-sentences-per-line/src/index.ts]: [Docs] Nit: a lot of the single-line comments added in this PR just restate what ~1-2 following lines do. I think it'd be easier to read those areas of code directly:

```suggestion
```

File: packages/prettier-plugin-sentences-per-line/src/index.ts [hunk 6]
```diff
@@ -20,19 +21,101 @@ export const parsers = {
...
+ * @see https://prettier.io/docs/plugins#print
+ */
+const print: PluginPrinter["print"] = (path, options, print, args) => {
+	const node = path.node;
+
+	/**
+	 * `sentence` nodes are printed as a grouped Doc so that they participate
+	 * correctly in line-breaking decisions and can be combined with
+	 * {@link breakParent} semantics.
+	 */
```
Comment (JoshuaKGoldberg) [inline packages/prettier-plugin-sentences-per-line/src/index.ts:72]: [Style] Nit: this JSDoc-style block comment isn't proper for a construct (`if` statement) that doesn't need a full JSDoc comment. Here it'd be more idiomatic to use `//`:

```suggestion
	 // `sentence` nodes are printed as a grouped Doc so that they participate
	 // correctly in line-breaking decisions and can be combined with
	 // {@link breakParent} semantics.
```

**Review by JoshuaKGoldberg — APPROVED** [review]
🔥 Wonderful, thanks! I appreciate you @marcalexiei iterating on this and @fisker's reviews. 

I have only a few small formatting/stylistic/types nitpicks, so I'll apply those myself and then merge. Much appreciated! ❤️

File: packages/prettier-plugin-sentences-per-line/src/index.ts (hunk 6 above)
Comment (JoshuaKGoldberg) [reply packages/prettier-plugin-sentences-per-line/src/index.ts:72]: _Oh_ the `{@link breakParent}` doesn't happen in non-JSDoc blocks. Lovely. Never mind then!

**Comment by fisker** [comment]
A note: prettier may stop generate `sentence` node in future, recently I found this makes no sense to split paragraph when `--prose-wrap=preserve` . We will change it, but won't happen soon.
